package io.github.feedbacklib.android.buildlogic.version

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Writes `SdkVersion.kt` with `internal const val SDK_VERSION` into [outputDir], so the library needs
 * no `BuildConfig`: that class is public, compiled by javac and invisible to the ABI dump.
 * Registered per variant in the module's build script via
 * `androidComponents.onVariants` + `Sources.addGeneratedSourceDirectory`, which sets [outputDir]
 * itself (under `build/generated/<source-type>/<variant>/<task name>`) — the task declares no
 * output location of its own.
 */
@CacheableTask
public abstract class GenerateSdkVersionTask : DefaultTask() {

    /** The artifact version, e.g. `0.1.0`. */
    @get:Input
    public abstract val sdkVersion: Property<String>

    /** Package of the generated constant. */
    @get:Input
    public abstract val packageName: Property<String>

    @get:OutputDirectory
    public abstract val outputDir: DirectoryProperty

    @TaskAction
    public fun generate() {
        val version = sdkVersion.get()
        // Only characters a Maven version uses: nothing that could end the string literal.
        if (!VERSION_PATTERN.matches(version)) throw GradleException("Unexpected SDK version for SdkVersion.kt: '$version'")
        val pkg = packageName.get()
        val root = outputDir.get().asFile
        root.deleteRecursively()
        val dir = File(root, pkg.replace('.', '/')).apply { mkdirs() }
        File(dir, "SdkVersion.kt").writeText(
            """
            |// Generated by :feedbackkit:generate<Variant>SdkVersion from gradle.properties (feedbackkit.version). Do not edit.
            |package $pkg
            |
            |/** Version of the SDK artifact, e.g. `0.1.0`. */
            |internal const val SDK_VERSION: String = "$version"
            |
            """.trimMargin(),
        )
    }

    private companion object {
        val VERSION_PATTERN = Regex("[0-9A-Za-z.+-]+")
    }
}
